# Generated by Django 4.0.1 on 2022-01-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mwodeola_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwodeolauser',
            name='secret_key',
            field=models.CharField(default=None, max_length=32, null=True),
        ),
    ]
