# Generated by Django 4.0.1 on 2022-01-26 05:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SNS',
            fields=[
                ('id', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('app_package_name', models.CharField(max_length=100)),
                ('web_url', models.URLField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AccountGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mwodeola_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mwodeola_user', to=settings.AUTH_USER_MODEL)),
                ('sns', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sns', to='accounts.sns')),
                ('group_name', models.CharField(max_length=30)),
                ('app_package_name', models.CharField(default=None, max_length=100, null=True)),
                ('web_url', models.URLField(default=None, max_length=100, null=True)),
                ('icon_type', models.SmallIntegerField(choices=[(0, 'TEXT'), (1, 'IMAGE'), (2, 'INSTALLED_APP_LOGO'), (3, 'SNS')], default=0)),
                ('icon_image_url', models.URLField(default=None, max_length=500, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_group', to='accounts.accountgroup')),
                ('user_id', models.CharField(max_length=50)),
                ('user_password', models.CharField(max_length=255)),
                ('user_password_pin', models.CharField(default=None, max_length=128, null=True)),
                ('user_password_pattern', models.CharField(default=None, max_length=128, null=True)),
                ('memo', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_confirmed_at', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sns_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account_sns_group', to='accounts.accountgroup')),
                ('own_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_own_group', to='accounts.accountgroup')),
                ('detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_detail', to='accounts.accountdetail')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('mwodeola_user', 'group_name'), name='Unique group name for user'),
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('mwodeola_user', 'sns'), name='Unique sns_group name for user'),
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('own_group', 'detail'), name='Unique detail within group'),
        ),
    ]
