# Generated by Django 4.0.1 on 2022-01-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountgroup',
            name='Unique group name for user',
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('mwodeola_user', 'group_name'), name='Unique group name for user'),
        ),
    ]
