# Generated by Django 4.0.1 on 2022-01-17 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_accountgroup_unique group name for user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountgroup',
            name='sns',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sns', to='accounts.sns'),
        ),
        migrations.AddConstraint(
            model_name='accountgroup',
            constraint=models.UniqueConstraint(fields=('mwodeola_user', 'sns'), name='Unique sns_group name for user'),
        ),
    ]
