# Generated by Django 4.0.1 on 2022-03-16 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_accountdetail_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountdetail',
            old_name='user_password_pin',
            new_name='user_password_pin4',
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='user_password_pin6',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
